### PR TITLE
Reinstall & Update translations + French translations

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi! This PR comes in replacement of #18 because I couldn't modify anything anymore on the previous PR so I started from scratch.

~~I installed translations to make all the languages available to translation, as many other apps.~~ I also separated the extra translations files (`desktop`, `appdata` and `polkit-policy`) into the  `po/extra` folder to make translation easier :smile:

I tried to build the app and this is working well. Here is the full changelog:

# Changelog

- [x] Remove existing translation files
- [X] Reinstall translations files ~~with predefined languages~~
- [X] Separate extra translations from main translations
- [X] Add the existing translations back (French and German)
- [X] Switch translations files to UTF-8
- [X] Make the build system look into `extra` directory for `desktop`, `appdata` and `polkit-policy` files
- [X] Update French translations

# Notice

Don't forget to add a new release before to publish the update :smile: 

This PR probably will have minor conflicts with #20. You should better merge #20 before this one, I'll take care of fixing the possible conflicts then.

**This PR is ready for review**

### CODE REVIEW

**Comment by bbuhler** [comment]
To be honest I don't like having all the languages already added.

I prefer to have an overview of what languages are currently supported. If someone wants to add translations for a not yet supported language they can adapt the LINGUAS file.

**Comment by NathanBnm** [comment]
> To be honest I don't like having all the languages already added.
> 
> I prefer to have an overview of what languages are currently supported. If someone wants to add translations for a not yet supported language they can adapt the LINGUAS file.

I understand your point, I made this because this prevent translators to create inconsistent translation files :smile: I'll remove them

**Comment by NathanBnm** [comment]
Ready now! :+1:

**Comment by NathanBnm** [comment]
Conflicts resolved 😉

**Pull request merged**
